<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PRJ2 Extractor\PRJ2 Extractor.csproj" />
    <Reference Include="TombLib">
      <HintPath>C:\Tomb Editor\TombLib.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

</Project>
